#!/bin/bash

echo "************ Refreshing Hive Tables*********"
hive --service beeline << EOF
!connect jdbc:hive2://10.0.4.10:10000 hadoop hadoop
show databases;
USE DTPIAUDITORDB;
show tables;
DESC IAUDITOR_INSPECTION_REPORT;
MSCK REPAIR TABLE IAUDITOR_INSPECTION_REPORT;
SELECT * FROM IAUDITOR_INSPECTION_REPORT;
desc ES_IAUDITOR_INSPECTION_REPORT;
INSERT OVERWRITE TABLE  ES_IAUDITOR_INSPECTION_REPORT   SELECT *  FROM IAUDITOR_INSPECTION_REPORT s;
SELECT * FROM ES_IAUDITOR_INSPECTION_REPORT;
EOF